apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      initContainers:
        - name: init-command
          image: debian
          command:
            - "echo hello Dev"

