apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend
  labels:
    type: nginx
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: content
          env:
            - name: SECRET_REPLACE
              valueFrom:
               secretKeyRef:
                 key:  SECRET_REPLACE
                 name: super-secrets
            - name: NOT_SECRET_REPLACE
              valueFrom:
                secretKeyRef:
                  key: DONT_OVERRIDE
                  name: super-secrets
      volumes:
        - name: content
          configMap:
            name: backend-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-content
data:
  index.html: |
    <H1>This is a basic backend!</H1>