# alias prod=
bases:
  - ../../base
  - ../security

commonLabels:
  env: prod
namePrefix: prod-
replicas:
  - name: frontend
    count: 3
  - name: backend
    count: 5
#patches:
#  - target:
#      group: apps
#      version: v1
#      kind: Deployment
#      labelSelector: "type=nginx"
#    path: image.yaml
#  - target:
#      kind: Deployment
#    path: ../security/root.yaml

