apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    metadata:
      annotations:
        security: stuff
    spec:
      securityContext:
        runAsNonRoot: true